steps:
  # 1. Build using google-22 builder and enable apt buildpack
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/olit-backend:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:google-22'
      - '--buildpack=google.apt'
      - '--buildpack=google.python.runtime'
      - '--buildpack=google.python.pip'
      - '--buildpack=google.config.entrypoint'
      - '--publish'
      - '--env=GOOGLE_RUNTIME_VERSION=3.11.*'
      - '--env=GOOGLE_ENTRYPOINT=gunicorn --bind 0.0.0.0:8080 app:app'

  # 2. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'olit-backend'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/olit-backend:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY